/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author davidespino
 */
public class homePage extends javax.swing.JFrame {

    /**=
     * Creates new form homePa
     */
    public homePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        returnMovie = new javax.swing.JButton();
        rentMovie = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        cuponCode = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnMovie.setBackground(new java.awt.Color(225, 225, 225));
        returnMovie.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        returnMovie.setText("Return");
        returnMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnMovieActionPerformed(evt);
            }
        });
        jPanel1.add(returnMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 230, 160));

        rentMovie.setBackground(new java.awt.Color(225, 225, 225));
        rentMovie.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        rentMovie.setText("Rent");
        rentMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentMovieActionPerformed(evt);
            }
        });
        jPanel1.add(rentMovie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 230, 160));

        welcome.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome to Xtra-Vision");
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 510, 150));

        cuponCode.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        cuponCode.setForeground(new java.awt.Color(255, 255, 255));
        cuponCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuponCode.setText("Your first rental is free. Use cupon code: FREEMOVIE  ");
        jPanel1.add(cuponCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon("/Users/davidespino/NetBeansProjects/XtraVision/src/view/pictures/background.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 990, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 978, 509));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnMovieActionPerformed
        //open the movieReturn window
          movieReturn f2= new movieReturn(); // create movieReturn object
          f2.setVisible(true);
          this.setVisible(false);
       
    }//GEN-LAST:event_returnMovieActionPerformed

    private void rentMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentMovieActionPerformed
        //Open movie window
          movie f3= new movie(); // create movie object
        f3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rentMovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel cuponCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rentMovie;
    private javax.swing.JButton returnMovie;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
