/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author davidespino
 */
public class movie extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    public movie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        capitanAmerica = new javax.swing.JButton();
        avengers = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capitanAmerica.setIcon(new javax.swing.ImageIcon("/Users/davidespino/NetBeansProjects/XtraVision/src/view/pictures/capitanAmerica.jpg")); // NOI18N
        capitanAmerica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capitanAmericaActionPerformed(evt);
            }
        });
        jPanel1.add(capitanAmerica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 170));

        avengers.setIcon(new javax.swing.ImageIcon("/Users/davidespino/NetBeansProjects/XtraVision/src/view/pictures/avengers.jpg")); // NOI18N
        avengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avengersActionPerformed(evt);
            }
        });
        jPanel1.add(avengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 130, 170));

        jButton4.setIcon(new javax.swing.ImageIcon("/Users/davidespino/NetBeansProjects/XtraVision/src/view/pictures/1917.jpeg")); // NOI18N
        jButton4.setMaximumSize(new java.awt.Dimension(166, 235));
        jButton4.setMinimumSize(new java.awt.Dimension(166, 235));
        jButton4.setPreferredSize(new java.awt.Dimension(166, 235));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 130, 170));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon("/Users/davidespino/NetBeansProjects/XtraVision/src/view/pictures/background.jpg")); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avengersActionPerformed
      // open movieDetail page    
        movieDetails f5= new movieDetails();
        f5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_avengersActionPerformed

    private void capitanAmericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capitanAmericaActionPerformed
        // open movieDetail page    
        movieDetails f5= new movieDetails();
        f5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_capitanAmericaActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       //Go Back
        homePage f4= new homePage(); // create movie object
        f4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // open movieDetail page    
        movieDetails f5= new movieDetails();
        f5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avengers;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JButton capitanAmerica;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
